'use client'

import { useEffect,useRef,useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

const choices=[['love_it','Love it'],['looks_good','Looks good'],['too_much_today','Too much today'],['too_easy','Too easy'],['not_feeling_workout','Not feeling this workout']] as const

export default function WorkoutFeedback({clientId,program,assignedWorkoutId,workoutTitle,workoutHref}:{clientId:string;program:'ember'|'ignite'|'phoenix';assignedWorkoutId:string;workoutTitle:string;workoutHref:string}){
  const router=useRouter();const panelRef=useRef<HTMLDivElement|null>(null);const [open,setOpen]=useState(false);const [response,setResponse]=useState('');const [note,setNote]=useState('');const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);const [offerLighter,setOfferLighter]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{if(!open)return;const outside=(event:MouseEvent|TouchEvent)=>{if(panelRef.current&&!panelRef.current.contains(event.target as Node))setOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};document.addEventListener('mousedown',outside);document.addEventListener('touchstart',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('mousedown',outside);document.removeEventListener('touchstart',outside);document.removeEventListener('keydown',escape)}},[open])
  async function submit(){if(!response)return;setSaving(true);setError('');try{const result=await fetch('/api/workout-feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,program,assignedWorkoutId,workoutTitle,response,note})});const payload=await result.json();if(!result.ok)throw new Error(payload.error||'Feedback could not be saved.');setSaved(true);setOfferLighter(Boolean(payload.offerLighter));router.refresh()}catch(value){setError(value instanceof Error?value.message:'Feedback could not be saved.')}finally{setSaving(false)}}
  return <div className="workout-feedback"><button type="button" className="workout-feedback-heart" aria-label="Give feedback on today’s workout" aria-expanded={open} onClick={()=>{setOpen(true);setSaved(false)}}>♡</button>{open?<div className="workout-feedback-backdrop"><div ref={panelRef} className="workout-feedback-panel" role="dialog" aria-modal="true" aria-label="Workout feedback"><button type="button" className="workout-feedback-close" onClick={()=>setOpen(false)} aria-label="Close feedback">×</button>{saved?<><span className="workout-feedback-saved">♥</span><h2>Got it.</h2><p>We&apos;ll use this to adjust your plan.</p>{offerLighter?<Link href={workoutHref} className="workout-feedback-primary">Open the lighter version</Link>:null}<button type="button" className="workout-feedback-secondary" onClick={()=>setOpen(false)}>Done</button></>:<><h2>How does today&apos;s plan feel?</h2><div className="workout-feedback-options">{choices.map(([value,label])=><button type="button" key={value} className={response===value?'selected':''} onClick={()=>setResponse(value)}>{label}</button>)}</div><label>Optional note<textarea value={note} onChange={(event)=>setNote(event.target.value)} maxLength={1000}/></label><button type="button" className="workout-feedback-primary" disabled={!response||saving} onClick={submit}>{saving?'Saving…':'Send Feedback'}</button>{error?<p role="alert">{error}</p>:null}</>}</div></div>:null}</div>
}
