'use client'

import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'

const practices={
  'breath-reset':{title:'Breath Reset',seconds:120,copy:'Two minutes to slow the pace and return to the next clear step.'},
  'calm-reset':{title:'Calm Reset',seconds:300,copy:'A gentle reset for a crowded nervous system.'},
  'sleep-wind-down':{title:'Sleep Wind Down',seconds:600,copy:'Lower the pace and prepare your body for sleep.'},
  'recovery-meditation':{title:'Recovery Meditation',seconds:480,copy:'Make space for recovery without turning it into another task.'},
} as const

export default function MeditationPractice({clientId,initialPractice}:{clientId:string;initialPractice:string}){const router=useRouter();const key=(initialPractice in practices?initialPractice:'breath-reset') as keyof typeof practices;const [practice,setPractice]=useState<keyof typeof practices>(key);const [remaining,setRemaining]=useState<number>(practices[key].seconds);const [running,setRunning]=useState(false);const current=practices[practice];useEffect(()=>{if(!running||remaining<=0)return;const timer=window.setInterval(()=>setRemaining((value)=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[running,remaining]);function choose(next:keyof typeof practices){setPractice(next);setRemaining(practices[next].seconds);setRunning(false)}async function complete(){setRunning(false);await fetch('/api/recovery/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,activityType:practice==='breath-reset'?'Breathwork':'Meditation',minutes:Math.max(2,Math.round((current.seconds-remaining)/60))})});router.refresh()}const phase=Math.floor((current.seconds-remaining)/4)%2===0?'Inhale':'Exhale';return <div className="meditation-practice"><nav aria-label="Meditation types">{(Object.keys(practices) as Array<keyof typeof practices>).map((item)=><button type="button" key={item} className={item===practice?'active':''} onClick={()=>choose(item)}>{practices[item].title}</button>)}</nav><section><p className="aos-eyebrow">{current.title}</p><div className={`meditation-flame ${running?(phase==='Inhale'?'inhale':'exhale'):''}`}><span aria-hidden="true">🔥</span></div><h1>{running?phase:current.title}</h1><p>{current.copy}</p><strong className="meditation-timer">{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</strong><div className="meditation-controls"><button type="button" onClick={()=>setRunning((value)=>!value)}>{running?'Pause':remaining<current.seconds?'Continue':'Start'}</button><button type="button" onClick={()=>{setRunning(false);setRemaining(current.seconds)}}>Reset</button><button type="button" onClick={complete}>Complete</button></div><small>Guided audio and Yoga Nidra support can be added to this practice library later.</small></section></div>}
